#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : golang-github-mattn-go-sqlite3
Version  : 467f50b0c026317ad28fc2c0a08aab6f755cfc7a
Release  : 2
URL      : https://github.com/mattn/go-sqlite3/archive/467f50b0c026317ad28fc2c0a08aab6f755cfc7a.tar.gz
Source0  : https://github.com/mattn/go-sqlite3/archive/467f50b0c026317ad28fc2c0a08aab6f755cfc7a.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : go

%description
go-sqlite3
==========
[![Build Status](https://travis-ci.org/mattn/go-sqlite3.svg?branch=master)](https://travis-ci.org/mattn/go-sqlite3)
[![Coverage Status](https://coveralls.io/repos/mattn/go-sqlite3/badge.svg?branch=master)](https://coveralls.io/r/mattn/go-sqlite3?branch=master)
[![GoDoc](https://godoc.org/github.com/mattn/go-sqlite3?status.svg)](http://godoc.org/github.com/mattn/go-sqlite3)

%prep
%setup -q -n go-sqlite3-467f50b0c026317ad28fc2c0a08aab6f755cfc7a

%build

%install
gopath="/usr/lib/golang"
library_path="github.com/mattn/go-sqlite3"
rm -rf %{buildroot}
install -d -p %{buildroot}${gopath}/src/${library_path}/
for file in $(find . -iname "*.go" -o -iname "*.h" -o -iname "*.c") ; do
     echo ${file}
     install -d -p %{buildroot}${gopath}/src/${library_path}/$(dirname $file)
     cp -pav $file %{buildroot}${gopath}/src/${library_path}/$file
done

%check
gopath="/usr/lib/golang"
export GOPATH="%{buildroot}${gopath}"
go test -v -x github.com/mattn/go-sqlite3

%files
%defattr(-,root,root,-)
/usr/lib/golang/src/github.com/mattn/go-sqlite3/_example/custom_func/main.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/_example/hook/hook.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/_example/mod_regexp/extension.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/_example/mod_regexp/sqlite3_mod_regexp.c
/usr/lib/golang/src/github.com/mattn/go-sqlite3/_example/mod_vtable/extension.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/_example/mod_vtable/picojson.h
/usr/lib/golang/src/github.com/mattn/go-sqlite3/_example/simple/simple.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/backup.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/callback.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/callback_test.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/doc.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/error.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/error_test.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/sqlite3-binding.c
/usr/lib/golang/src/github.com/mattn/go-sqlite3/sqlite3-binding.h
/usr/lib/golang/src/github.com/mattn/go-sqlite3/sqlite3.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/sqlite3_fts3_test.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/sqlite3_fts5.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/sqlite3_icu.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/sqlite3_json1.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/sqlite3_libsqlite3.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/sqlite3_load_extension.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/sqlite3_omit_load_extension.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/sqlite3_other.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/sqlite3_test.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/sqlite3_test/sqltest.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/sqlite3_windows.go
/usr/lib/golang/src/github.com/mattn/go-sqlite3/sqlite3ext.h
